"""empty message

Revision ID: 67151dbed5df
Revises: b7ba371a9bc9
Create Date: 2020-10-04 18:26:29.519081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67151dbed5df'
down_revision = 'b7ba371a9bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
